name: "Terraform: cloud-dev-vm"

on:
  push:
    branches: [master]
    paths: [infra/cloud-dev-vm/**, .github/workflows/terraform-cloud-dev-vm.yml, .github/workflows/terraform.yml]
  pull_request:
    paths: [infra/cloud-dev-vm/**, .github/workflows/terraform-cloud-dev-vm.yml, .github/workflows/terraform.yml]

concurrency:
  group: terraform-cloud-dev-vm-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      module_name: cloud-dev-vm
      terraform_vars: '-var="project_id=${{ vars.GCP_PROJECT_ID }}"'
    permissions:
      contents: read
      id-token: write
      pull-requests: write
